### ISSUE TITLE
添加了 404 页面

### ISSUE THREAD

**Issue by emptymalei** [InterImm/interimm.github.io#23]
就是直接用了我自己的以前的，大家有什么好的脑洞可以来说说看。

随便输入一个我们网站没有的页面，比如

http://interimm.org/abdcs

可以看到。

**Comment by ProtossProbe** [comment]
感觉内容有点多，我觉得简洁一点比较好

**Comment by emptymalei** [comment]
快来说说去掉哪些

**Comment by ProtossProbe** [comment]
搜索框感觉也没什么必要，而且与页面风格不搭

**Comment by emptymalei** [comment]
@ProtossProbe 等我有时间了去设计一个跟主页风格一样的。

现在倒是确定 404 可以工作了，而且在全站工作，星际移民之书什么的也会自动用这个 404 。

**Comment by emptymalei** [comment]
@ProtossProbe 对了，我觉得搜索需要留着，以前我统计过数据，有搜索的话可以大大降低 bounce rate，也就是说，没有搜索的话，很多人会直接关掉页面，加了搜索有很大的比例会去搜一下，再次进入到我们的站点。
应该换个搜索，不能用 google 了。

**Comment by unionx** [comment]
http://interimm.org/ 主站是用的 Jekyll？我记得 Jekyll 有搜索插件的

**Comment by emptymalei** [comment]
@unionx 主站不是用的 jekyll

我们的 jekyll 也不能用插件，因为我们想让 GitHub 自动给我们自动生成。而 GitHub Pages 自动禁用了 jekyll 的插件们，如果用来插件只能自己手动生成再 push 上来，太麻烦了。现在我们自动生成可以借助 prose.io 来像写博客一样写（虽然 prose 不太稳定）。

另外，jekyll 的搜索可以借助第三方索引服务来实现，例如 https://swiftype.com/ 就是很好的选择。

**Comment by unionx** [comment]
=。= 实在不行，用必应也是可以接受的

**Comment by emptymalei** [comment]
@unionx swifttype 是非常非常棒的，你可以去瞧一眼。

**Comment by styra** [comment]
@emptymalei 感觉那个分隔线不太好看，主要是中间有个章节符号怪怪的。
您正在寻找的页面已丢失或不存在，可能您进入了错误了时间分区，相关档案尚未创建。请在底部搜索、返回首页或者退回之前页面。

**Comment by emptymalei** [comment]
@styra 好的，等综合考虑一下大家的意见重新做一个。

**Comment by emptymalei** [comment]
重新做了一个。用了这个：http://codepen.io/Garvit/pen/bNgmEW/

还有一个也不错：http://codepen.io/emptymalei/pen/PwgNrJ  不过没用

**Comment by ProtossProbe** [comment]
帅哭

**Comment by ProtossProbe** [comment]
刚才想到，404的界面的“档案丢失”可以换个更贴合这个界面的说法
比如说：
“档案遗失于群星的尽头”
之类的东西......

**Comment by emptymalei** [comment]
有看到了这个 404 页面，实在太美了。所以关掉这个 issue 吧。
