### ISSUE TITLE
官网 redesign

### ISSUE THREAD

**Issue by ProtossProbe** [InterImm/interimm.github.io#25]
心血来潮重新设计了一下官网，做了张图，但是由于太渣并不知道怎么用 html 和 css 实现.....= = 先放在这里。
![desktop hd](https://cloud.githubusercontent.com/assets/6406279/9031697/7069686e-3984-11e5-81cc-59dcbac136a7.png)

**Comment by unionx** [comment]
棒！来改版吧！

**Comment by emptymalei** [comment]
感觉这样的话跟其它版面的导航条就不统一了呢，等我们来重新讨论一下版面的问题，目前有点不够整洁。

**Comment by ProtossProbe** [comment]
我也觉得圆桌一多官网就显得乱乱的，抓不住重点。
另外导航栏的话有些功能有些没必要，比如“星际机构”和“果壳小组”

**Comment by emptymalei** [comment]
可是如果不加上的话，别人就没法找了。

**Comment by ProtossProbe** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/6406279/9042574/9550cb50-39dd-11e5-9b07-d853e2ec772f.png)
刚刚又重新改了一点，上面的位置空了出来，如果把导航栏加上也是可以的

**Comment by emptymalei** [comment]
还有一个问题，就是有了新的活动通知的地方也去掉了呢？

**Comment by ProtossProbe** [comment]
我觉得星际机构和工具箱没有必要放在导航栏里面...可以放在版面的其他的地方

**Comment by ProtossProbe** [comment]
这只是一个初稿......还需要什么的东西应该可以再加，留白的地方还是很多的

**Comment by emptymalei** [comment]
嗯嗯

**Comment by ProtossProbe** [comment]
另外我用的是sketch做的，好像可以直接复制css属性什么的....

**Comment by emptymalei** [comment]
当前在用的是 bootstrap 框架，我个人不太同意换掉框架，如果要换掉的话那么我们就整站全换掉，包括那些文档什么的。在不同的框架下面工作最容易出现的后果就是在不同的平台不同的浏览器出现不一样的反应。

**Comment by ProtossProbe** [comment]
我并没有说要换掉框架，所以基本上是按照 12 个 colume 来对其的。具体屏幕分辨率切换后的反应不知道好不好实现...

**Comment by emptymalei** [comment]
建一个新的 branch 然后 push 上来吧，我们来一起改改。

**Comment by emptymalei** [comment]
话说我不知道 sketch 是什么，我以为是那种用来做模板的，是个画图的工具？如果是这样的话，好像 CSS拿来也没用，应该自己用来写，因为我们需要用 bootstrap 自己的属性来弄吧？

我上面提到的不同的屏幕平台不同的浏览器的反应，是说假定我们有个页面不用 bootstrap 框架，是自己写的 html css js，那么跟其它页面就可能处在在 chome 导航栏相同，但是在 firefox 中导航栏不同的情况，如果还决定要保存导航栏的话。

至于屏幕分辨率的切换，这个是 responsive 完成的，bootstrap 自带的，要自己写的话比较麻烦些。

-----

我突然想起，如果这样的设计模式的话，Proj, Diss 这个缩写有点奇怪，而且有点太大，这样跟很少的内容对比太明显。

我仔细想了想，目前导航栏里面的东西，当时也是想过的，算是那种 global 的东西，比如在阅读什么的时候，发现有个什么地方要查找，可以立刻切换到工具箱之类的。GitHub 那个倒是没必要所有页面都有。

----

还是把这个草稿放上来，我们都看看吧，这样只看图的话，感觉讨论不透。

**Comment by emptymalei** [comment]
哦，我明白了，这个只有图么？

**Comment by unionx** [comment]
感觉可以拉一个 develop 分支出来开发啊

**Comment by ProtossProbe** [comment]
这个就只是一个图啊😂
Sketch 就相当于 Ps 一样的画图软件而已

**Comment by ProtossProbe** [comment]
那几个大字的地方觉得不妥的话可以用一些图来代替？

**Comment by emptymalei** [comment]
大字改小了好看么？

-----
原来是个做图软件。
