### ISSUE TITLE
Redesign 2018

### ISSUE THREAD

**Issue by emptymalei** [InterImm/interimm.github.io#35]
# 官网重新组织

## 为什么

1. 现在网站太多了，用了不同的技术，在不同的地方，很多很少的内容但是用了完整的一个网站。
2. 如果我们有什么更新，首页没法体现出来。如果经常更新首页html又很头疼。
3. 需要一个新的样式了，很久没变了。

## 方案

我现在有两套大致的方案。
1. 首页使用 Jekyll，作为主站，然后其他的相关的内容作为 submodule 来加入到主站来，这样不用维护很多个不同的小网站，而且风格统一。
2. 还是单独的，只是把样式各自更新，然后换上一些新的技术。

我更倾向于用第一条。虽然 Jekyll 是很老了，但是我们这个网站群有点大，别的技术我好像暂时驾驭不了。

## 实施

- [x] 建立主站 Jekyll: #36 
- [x] 重新整理
   - [x] stellar
   - [x] cities
   - [x] magazine
   - [x] roundTable (which is currently partially included in magitine)
   - [x] solarsystem
- [x] 整理链接

**Comment by emptymalei** [comment]
@unionx 好啊，我上周末把框架搭起来了。等我这周末写个 todo list 什么的就好了。

**Comment by unionx** [comment]
好的！

**Comment by emptymalei** [comment]
@unionx 

我觉得有几个大的部分需要做。

## 主站

我自己差不多重构了一下主站。

- [x] 换成 Jekyll
- [x] 创建 index.html
- [x] 创建 institutes.html
- [x] 创建 toolbox.html
- [ ] 创建 404.html （我完成了一半）

## 文档

所有的文档需要把 gh-pages 当作子站，这样就可以直接出现在 jekyll 里面了。

但是需要统一样式，这个我还不知道怎么实现。大概可能有两个吧：
1. 用 Python 或者什么办法来自动把 jekyll 的导航栏更新到这些 sphinx 生成的页面里面
2. Jekyll 用上 rst 插件？我觉得这个有点不方便，还要设计新的页面样式。

或者就不管了，直接把这些其他的 repo 里面的 html 拿过来好了，具体的 导航栏匹配什么的记得在 sphinx 里面做。

## 工具

工具类的页面，可能需要整理出来，比如展示在一个页面里面之类的。

**Comment by unionx** [comment]
设计 footer 的目标是？我可以来设计和改这块的代码

**Comment by emptymalei** [comment]
@unionx footer 我做好了。
其实工作量不是很大，如果你想看看可以瞧瞧 `jekyll` branch

**Comment by emptymalei** [comment]
@unionx 帝老师我把框架搭起来了，你看看还有什么问题。
